---
- name: YUM - Install dependencies
  ansible.builtin.yum:
    name: "{{ dependencies[ansible_distribution] }}"
  become: true
  when: ansible_distribution not in ["Ubuntu"]

- name: YUM - Configure repositories
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: "{{ repositories[ansible_distribution].url }}"
    gpgkey: "{{ repositories[ansible_distribution]['keys'] }}"
    enabled: true
    gpgcheck: true
    exclude:
      - kubelet
      - kubeadm
      - kubectl
  become: true
  when: ansible_distribution == "CentOS"

- name: YUM - Install packages
  ansible.builtin.yum:
    name: "{{ packages[ansible_distribution] }}"
    disable_excludes: kubernetes
  become: true
  when: ansible_distribution not in ["Ubuntu"]

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  become: true

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
  become: true
